version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "13134:13134"

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && node dist/index.js"

volumes:
  pgdata:
